//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_Customers_Category", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Solution.Bussines.Entities.Category), "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Solution.Bussines.Entities.Customers))]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_RegistroTiemposParqueo_Carros", "Carros", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Solution.Bussines.Entities.Carros), "RegistroTiemposParqueo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Solution.Bussines.Entities.RegistroTiemposParqueo), true)]

#endregion

namespace Solution.Bussines.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CustomersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CustomersEntities object using the connection string found in the 'CustomersEntities' section of the application configuration file.
        /// </summary>
        public CustomersEntities() : base("name=CustomersEntities", "CustomersEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomersEntities object.
        /// </summary>
        public CustomersEntities(string connectionString) : base(connectionString, "CustomersEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomersEntities object.
        /// </summary>
        public CustomersEntities(EntityConnection connection) : base(connection, "CustomersEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Category
        {
            get
            {
                if ((_Category == null))
                {
                    _Category = base.CreateObjectSet<Category>("Category");
                }
                return _Category;
            }
        }
        private ObjectSet<Category> _Category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customers> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customers>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customers> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Carros> Carros
        {
            get
            {
                if ((_Carros == null))
                {
                    _Carros = base.CreateObjectSet<Carros>("Carros");
                }
                return _Carros;
            }
        }
        private ObjectSet<Carros> _Carros;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RegistroTiemposParqueo> RegistroTiemposParqueo
        {
            get
            {
                if ((_RegistroTiemposParqueo == null))
                {
                    _RegistroTiemposParqueo = base.CreateObjectSet<RegistroTiemposParqueo>("RegistroTiemposParqueo");
                }
                return _RegistroTiemposParqueo;
            }
        }
        private ObjectSet<RegistroTiemposParqueo> _RegistroTiemposParqueo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customers customers)
        {
            base.AddObject("Customers", customers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Carros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarros(Carros carros)
        {
            base.AddObject("Carros", carros);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RegistroTiemposParqueo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistroTiemposParqueo(RegistroTiemposParqueo registroTiemposParqueo)
        {
            base.AddObject("RegistroTiemposParqueo", registroTiemposParqueo);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        public ObjectResult<Customers> getCustomersByName(global::System.String name)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Customers>("getCustomersByName", nameParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="name">No Metadata Documentation available.</param>
        public ObjectResult<Customers> getCustomersByName(global::System.String name, MergeOption mergeOption)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Customers>("getCustomersByName", mergeOption, nameParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Carros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carros : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Carros object.
        /// </summary>
        /// <param name="placa">Initial value of the Placa property.</param>
        /// <param name="esResidente">Initial value of the EsResidente property.</param>
        public static Carros CreateCarros(global::System.String placa, global::System.Boolean esResidente)
        {
            Carros carros = new Carros();
            carros.Placa = placa;
            carros.EsResidente = esResidente;
            return carros;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Placa
        {
            get
            {
                return _Placa;
            }
            set
            {
                if (_Placa != value)
                {
                    OnPlacaChanging(value);
                    ReportPropertyChanging("Placa");
                    _Placa = StructuralObject.SetValidValue(value, false, "Placa");
                    ReportPropertyChanged("Placa");
                    OnPlacaChanged();
                }
            }
        }
        private global::System.String _Placa;
        partial void OnPlacaChanging(global::System.String value);
        partial void OnPlacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EsResidente
        {
            get
            {
                return _EsResidente;
            }
            set
            {
                OnEsResidenteChanging(value);
                ReportPropertyChanging("EsResidente");
                _EsResidente = StructuralObject.SetValidValue(value, "EsResidente");
                ReportPropertyChanged("EsResidente");
                OnEsResidenteChanged();
            }
        }
        private global::System.Boolean _EsResidente;
        partial void OnEsResidenteChanging(global::System.Boolean value);
        partial void OnEsResidenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentari
        {
            get
            {
                return _Comentari;
            }
            set
            {
                OnComentariChanging(value);
                ReportPropertyChanging("Comentari");
                _Comentari = StructuralObject.SetValidValue(value, true, "Comentari");
                ReportPropertyChanged("Comentari");
                OnComentariChanged();
            }
        }
        private global::System.String _Comentari;
        partial void OnComentariChanging(global::System.String value);
        partial void OnComentariChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EsVisitante
        {
            get
            {
                return _EsVisitante;
            }
            set
            {
                OnEsVisitanteChanging(value);
                ReportPropertyChanging("EsVisitante");
                _EsVisitante = StructuralObject.SetValidValue(value, "EsVisitante");
                ReportPropertyChanged("EsVisitante");
                OnEsVisitanteChanged();
            }
        }
        private Nullable<global::System.Boolean> _EsVisitante;
        partial void OnEsVisitanteChanging(Nullable<global::System.Boolean> value);
        partial void OnEsVisitanteChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_RegistroTiemposParqueo_Carros", "RegistroTiemposParqueo")]
        public EntityCollection<RegistroTiemposParqueo> RegistroTiemposParqueo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RegistroTiemposParqueo>("DatabaseModel.FK_RegistroTiemposParqueo_Carros", "RegistroTiemposParqueo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RegistroTiemposParqueo>("DatabaseModel.FK_RegistroTiemposParqueo_Carros", "RegistroTiemposParqueo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Category CreateCategory(global::System.Int32 id)
        {
            Category category = new Category();
            category.Id = id;
            return category;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Customers_Category", "Customers")]
        public EntityCollection<Customers> Customers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customers>("DatabaseModel.FK_Customers_Category", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customers>("DatabaseModel.FK_Customers_Category", "Customers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Customers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customers object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Customers CreateCustomers(global::System.Int32 id, global::System.String name)
        {
            Customers customers = new Customers();
            customers.Id = id;
            customers.Name = name;
            return customers;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Customers_Category", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("DatabaseModel.FK_Customers_Category", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("DatabaseModel.FK_Customers_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("DatabaseModel.FK_Customers_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("DatabaseModel.FK_Customers_Category", "Category", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="RegistroTiemposParqueo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegistroTiemposParqueo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RegistroTiemposParqueo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="placa">Initial value of the Placa property.</param>
        /// <param name="horaIngreso">Initial value of the HoraIngreso property.</param>
        public static RegistroTiemposParqueo CreateRegistroTiemposParqueo(global::System.Int32 id, global::System.String placa, global::System.DateTime horaIngreso)
        {
            RegistroTiemposParqueo registroTiemposParqueo = new RegistroTiemposParqueo();
            registroTiemposParqueo.Id = id;
            registroTiemposParqueo.Placa = placa;
            registroTiemposParqueo.HoraIngreso = horaIngreso;
            return registroTiemposParqueo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Placa
        {
            get
            {
                return _Placa;
            }
            set
            {
                OnPlacaChanging(value);
                ReportPropertyChanging("Placa");
                _Placa = StructuralObject.SetValidValue(value, false, "Placa");
                ReportPropertyChanged("Placa");
                OnPlacaChanged();
            }
        }
        private global::System.String _Placa;
        partial void OnPlacaChanging(global::System.String value);
        partial void OnPlacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HoraIngreso
        {
            get
            {
                return _HoraIngreso;
            }
            set
            {
                OnHoraIngresoChanging(value);
                ReportPropertyChanging("HoraIngreso");
                _HoraIngreso = StructuralObject.SetValidValue(value, "HoraIngreso");
                ReportPropertyChanged("HoraIngreso");
                OnHoraIngresoChanged();
            }
        }
        private global::System.DateTime _HoraIngreso;
        partial void OnHoraIngresoChanging(global::System.DateTime value);
        partial void OnHoraIngresoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HoraSalida
        {
            get
            {
                return _HoraSalida;
            }
            set
            {
                OnHoraSalidaChanging(value);
                ReportPropertyChanging("HoraSalida");
                _HoraSalida = StructuralObject.SetValidValue(value, "HoraSalida");
                ReportPropertyChanged("HoraSalida");
                OnHoraSalidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _HoraSalida;
        partial void OnHoraSalidaChanging(Nullable<global::System.DateTime> value);
        partial void OnHoraSalidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TiempoAcumulado
        {
            get
            {
                return _TiempoAcumulado;
            }
            set
            {
                OnTiempoAcumuladoChanging(value);
                ReportPropertyChanging("TiempoAcumulado");
                _TiempoAcumulado = StructuralObject.SetValidValue(value, "TiempoAcumulado");
                ReportPropertyChanged("TiempoAcumulado");
                OnTiempoAcumuladoChanged();
            }
        }
        private Nullable<global::System.Int32> _TiempoAcumulado;
        partial void OnTiempoAcumuladoChanging(Nullable<global::System.Int32> value);
        partial void OnTiempoAcumuladoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EstaParqueado
        {
            get
            {
                return _EstaParqueado;
            }
            set
            {
                OnEstaParqueadoChanging(value);
                ReportPropertyChanging("EstaParqueado");
                _EstaParqueado = StructuralObject.SetValidValue(value, "EstaParqueado");
                ReportPropertyChanged("EstaParqueado");
                OnEstaParqueadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _EstaParqueado;
        partial void OnEstaParqueadoChanging(Nullable<global::System.Boolean> value);
        partial void OnEstaParqueadoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_RegistroTiemposParqueo_Carros", "Carros")]
        public Carros Carros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Carros>("DatabaseModel.FK_RegistroTiemposParqueo_Carros", "Carros").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Carros>("DatabaseModel.FK_RegistroTiemposParqueo_Carros", "Carros").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Carros> CarrosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Carros>("DatabaseModel.FK_RegistroTiemposParqueo_Carros", "Carros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Carros>("DatabaseModel.FK_RegistroTiemposParqueo_Carros", "Carros", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
